import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

export const contentSnapshots = pgTable('content_snapshots', {
  contentType: text('content_type').notNull(),
  snapshotKey: text('snapshot_key').primaryKey(),
  payload: jsonb('payload').notNull(),
  payloadHash: text('payload_hash').notNull(),
  capturedAt: timestamp('captured_at', { withTimezone: true }).notNull().defaultNow(),
  usedAt: timestamp('used_at', { withTimezone: true }),
});

export const rebuildEvents = pgTable(
  'rebuild_events',
  {
    id: text('id').primaryKey(),
    source: text('source').notNull().default('wordpress'),
    contentType: text('content_type').notNull(),
    contentId: text('content_id').notNull(),
    slug: text('slug').notNull(),
    transition: text('transition').notNull(),
    status: text('status').notNull().default('pending'),
    payload: jsonb('payload').notNull(),
    eventHash: text('event_hash').notNull(),
    sourceIp: text('source_ip').notNull(),
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }).notNull(),
    processedAt: timestamp('processed_at', { withTimezone: true }),
    deployStartedAt: timestamp('deploy_started_at', { withTimezone: true }),
    deployTriggeredAt: timestamp('deploy_triggered_at', { withTimezone: true }),
    deployHookId: text('deploy_hook_id'),
    deployJobId: text('deploy_job_id'),
    deployJobState: text('deploy_job_state'),
    deployJobCreatedAt: timestamp('deploy_job_created_at', { withTimezone: true }),
    deployFinishedAt: timestamp('deploy_finished_at', { withTimezone: true }),
    buildDurationMs: integer('build_duration_ms'),
    deployResponseStatus: integer('deploy_response_status'),
    deploymentId: text('deployment_id'),
    deploymentState: text('deployment_state'),
    deploymentUrl: text('deployment_url'),
    error: text('error'),
    longBuildReviewRequired: boolean('long_build_review_required').notNull().default(false),
  },
  (table) => [
    uniqueIndex('rebuild_events_event_hash_idx').on(table.eventHash),
    index('rebuild_events_status_scheduled_at_idx').on(table.status, table.scheduledAt),
    index('rebuild_events_status_triggered_at_idx').on(table.status, table.deployTriggeredAt),
  ],
);
